export enum Intent {

  EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY",

  INVENTORY_STATUS = "INVENTORY_STATUS",

  REORDER_DECISION = "REORDER_DECISION",

  OVERSTOCK_ANALYSIS = "OVERSTOCK_ANALYSIS",

  DEAD_STOCK_ANALYSIS = "DEAD_STOCK_ANALYSIS",

  FINANCIAL_IMPACT = "FINANCIAL_IMPACT",

  BUSINESS_HEALTH = "BUSINESS_HEALTH",

  PRODUCT_ANALYSIS = "PRODUCT_ANALYSIS",

  DEMAND_FORECAST = "DEMAND_FORECAST",

  UNKNOWN = "UNKNOWN",

}